### ISSUE TITLE
Feature Request: HQ symbol

### ISSUE THREAD

**Issue by bendy101** [Metis-Team/mts_marker#74] opened 2023-10-25 05:28 UTC
The current symbol for HQ is only an element, it is not actually a HQ symbol, which for NATO is basically a vertical line on the left outside the box going downwards. Example here:
![image](https://github.com/Metis-Team/mts_marker/assets/29008740/f7050efb-cbbb-4993-897b-91a95b5a746e)

I suggest a checkbox in the popup next to "suspect" checkbox to select it.

**Comment by bendy101** [comment] 2023-10-25 05:33
ok just realised this is a duplicate. No idea how to delete

**Comment by Timi007** [comment] 2023-10-25 11:42
Duplicate of #46

**Closed by Timi007** 2023-10-25 11:42 UTC
Labels: feature request
