### ISSUE TITLE
Feature request: the HQ symbol

### ISSUE THREAD

**Issue by bendy101** [Metis-Team/mts_marker#73] opened 2023-10-09 01:22 UTC
was amazed to see this mod doesnt have one of the most important markers, the HQ!!

it looks like this:

blufor:
https://commons.wikimedia.org/wiki/File:NATO_Map_Symbol_-_Friendly_Headquarters.svg

opfor
https://commons.wikimedia.org/wiki/File:NATO_Map_Symbol_-_Enemy_Headquarters.svg

please add :)

**Comment by Timi007** [comment] 2023-10-09 14:37
Duplicate of #46

**Closed by Timi007** 2023-10-09 14:37 UTC
Labels: feature request
